global:
  scrape_interval: 15s # Frequenza di scrape

scrape_configs:
  - job_name: 'flask-app-rag'
    # 'app:8000' è l'hostname (definito in docker-compose) e la porta
    # della nostra applicazione RAG
    static_configs:
      - targets: ['app:8000']
        # L'endpoint /metrics è fornito da prometheus-flask-exporter